artifacts_root: 'artifacts/'

data_ingestion:
  root_dir: 'artifacts/dataIngestion/'
  source_URL: source_URL = "https://drive.google.com/uc?export=download&id=1lFVGDILzcfEG5yEgdIgPdoC0zyJpoWZp"
  local_data_file: 'artifacts/dataIngestion/data.zip'
  unzip_dir: 'artifacts/dataIngestion/'
