artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/dataIngestion
  source_URL: https://drive.google.com/file/d/1lFVGDILzcfEG5yEgdIgPdoC0zyJpoWZp/view?usp=sharing
  local_data_file: artifacts/dataIngestion/data.zip
  unzip_dir: artifacts/dataIngestion